

# single : ml_plos.py
# 		python ml_plos.py

clean:
	rm -f *.pyc ../data/*.txt ../data/*.png ../data/*.npz
	rm -f ../data/*.pdf
	rm -f ../data/fig/*
	rm -f ../data/npz/*
	@echo "cleaned up"

help:
	@echo "    clean"
	@echo "         Remove python artifacts."


.phoney: clean #single 
