

# single : ml_plos.py
# 		python ml_plos.py

clean:
	rm -f *.pyc
	rm -f ../data/*.pdf
	rm -f ../data/fig/*
	rm -f ../data/npz/*
	rm -f ../data/text/*
	@echo "cleaned up"

help:
	@echo "    clean"
	@echo "         Remove python artifacts."


.phoney: clean #single 
